CREATE DATABASE [MeridianExampleDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MeridianExampleDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\MeridianExampleDB.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MeridianExampleDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\MeridianExampleDB_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [MeridianExampleDB] SET COMPATIBILITY_LEVEL = 140
GO
ALTER DATABASE [MeridianExampleDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MeridianExampleDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MeridianExampleDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MeridianExampleDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MeridianExampleDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [MeridianExampleDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MeridianExampleDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MeridianExampleDB] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [MeridianExampleDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MeridianExampleDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MeridianExampleDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MeridianExampleDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MeridianExampleDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MeridianExampleDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MeridianExampleDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MeridianExampleDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MeridianExampleDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MeridianExampleDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MeridianExampleDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MeridianExampleDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MeridianExampleDB] SET  READ_WRITE 
GO
ALTER DATABASE [MeridianExampleDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MeridianExampleDB] SET  MULTI_USER 
GO
ALTER DATABASE [MeridianExampleDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MeridianExampleDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MeridianExampleDB] SET DELAYED_DURABILITY = DISABLED 
GO
USE [MeridianExampleDB]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [MeridianExampleDB]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [MeridianExampleDB] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
